### ISSUE TITLE
弹幕按钮及字幕加载问题

### ISSUE THREAD

**Issue by EdenBob** [MoePlayer/DPlayer-Typecho#13]
![QQ截图20190612211306](https://user-images.githubusercontent.com/47360310/59354113-01993600-8d57-11e9-906f-8c73cf05ad78.png)
如图，弹幕按钮显示不全

**Comment by EdenBob** [comment]
插件能否实现加载.srt字幕

**Comment by volio** [comment]
弹幕按钮可能是因为其他CSS样式冲突导致，srt字幕加载需要DPlayer主项目支持
