### ISSUE TITLE
Dplayer的screenshot参数在type博客的插件中不起作用

### ISSUE THREAD

**Issue by EdenBob** [MoePlayer/DPlayer-Typecho#15]
![QQ截图20190702184127](https://user-images.githubusercontent.com/47360310/60506771-30bd1a80-9cf9-11e9-8f9c-769341b52f1f.png)
![QQ截图20190702184101](https://user-images.githubusercontent.com/47360310/60506773-30bd1a80-9cf9-11e9-949b-ae029c54f1b3.png)

**Comment by volio** [comment]
screenshot参数暂不支持

**Comment by volio** [comment]
最新版本已支持 screenshot 和 loop 参数
