### ISSUE TITLE
2022.5.17无法使用

### ISSUE THREAD

**Issue by collinsqq** [MoePlayer/DPlayer-Typecho#37]
我和我的朋友们网站的Dplayer都出现了无法使用的情况，是的，以前一直都正常的，但今天发现，播放器所占的位置变成了全透明状态。

**Comment by collinsqq** [comment]
我似乎发现了，原有的https://cdn.jsdelivr.net/npm/dplayer/dist/DPlayer.min.js无法访问了

**Comment by lyl86** [comment]
fixed
